/**
 * Generates fresh throwaway wallets for the seller (payTo) and buyer, writes the
 * private keys into .env, and prints ONLY the public addresses.
 *
 * The private keys are never printed to the terminal and never leave this
 * machine. .env is gitignored.
 *
 * These are disposable hackathon wallets. Fund them with a few dollars at most.
 * Never point this at, or paste in, a key that holds anything you care about.
 *
 * Run: npm run new-wallets
 */
import { appendFileSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";

const ENV_PATH = new URL("../.env", import.meta.url).pathname;

if (!existsSync(ENV_PATH)) {
  console.error(
    ".env not found. Run `cp .env.example .env` first, then re-run this.",
  );
  process.exit(1);
}

const env = readFileSync(ENV_PATH, "utf8");

/** Refuse to clobber a key that already exists and looks real. */
function alreadySet(key: string): boolean {
  const match = env.match(new RegExp(`^${key}=(.*)$`, "m"));
  return Boolean(match?.[1] && match[1].trim().length > 10);
}

const wantSeller = !alreadySet("SELLER_PRIVATE_KEY");
const wantBuyer = !alreadySet("BUYER_PRIVATE_KEY");

if (!wantSeller && !wantBuyer) {
  console.log(
    "Both SELLER_PRIVATE_KEY and BUYER_PRIVATE_KEY are already set in .env.\n" +
      "Nothing generated. Delete those lines first if you really want new wallets.",
  );
  const sellerAddr = process.env.SELLER_ADDRESS ?? "(see .env)";
  console.log(`seller: ${sellerAddr}`);
  process.exit(0);
}

const lines: string[] = ["", "# generated by scripts/new-wallets.ts — do not commit"];
const printed: { label: string; address: string }[] = [];

if (wantSeller) {
  const key = generatePrivateKey();
  const account = privateKeyToAccount(key);
  lines.push(`SELLER_PRIVATE_KEY=${key}`);
  printed.push({ label: "SELLER (payTo, receives payments)", address: account.address });
  // PAY_TO_ADDRESS drives the server's payment requirements.
  if (/^PAY_TO_ADDRESS=.*$/m.test(env)) {
    writeFileSync(
      ENV_PATH,
      readFileSync(ENV_PATH, "utf8").replace(
        /^PAY_TO_ADDRESS=.*$/m,
        `PAY_TO_ADDRESS=${account.address}`,
      ),
    );
  } else {
    lines.push(`PAY_TO_ADDRESS=${account.address}`);
  }
}

if (wantBuyer) {
  const key = generatePrivateKey();
  const account = privateKeyToAccount(key);
  lines.push(`BUYER_PRIVATE_KEY=${key}`);
  printed.push({ label: "BUYER (pays, needs USDC)", address: account.address });
}

appendFileSync(ENV_PATH, lines.join("\n") + "\n");

/**
 * .env.example ships placeholder keys with empty values (e.g. BUYER_PRIVATE_KEY=).
 * Appending a real value leaves the key assigned twice, and dotenv honours the
 * FIRST occurrence — so the generated key would be silently ignored at runtime.
 * Strip any empty-valued duplicate whose key now has a real value.
 */
{
  const current = readFileSync(ENV_PATH, "utf8").split("\n");
  const hasValue = new Set(
    current
      .map((l) => /^([A-Z0-9_]+)=(.*)$/.exec(l))
      .filter((m): m is RegExpExecArray => Boolean(m && m[2]?.trim()))
      .map((m) => m[1]!),
  );
  const deduped = current.filter((line) => {
    const m = /^([A-Z0-9_]+)=(.*)$/.exec(line);
    return !(m && !m[2]?.trim() && hasValue.has(m[1]!));
  });
  writeFileSync(ENV_PATH, deduped.join("\n"));
}

console.log("Wrote new keys into .env. They were not printed here.\n");
for (const { label, address } of printed) {
  console.log(`${label}\n  ${address}\n`);
}
console.log(
  "Next: fund the BUYER address with a small amount of USDC on Celo mainnet\n" +
    "  USDC on Celo: 0xcebA9300f2b948710d2653dD7B07f33A8B32118C (6 decimals)\n" +
    "Then paste the two addresses above (addresses only, never the keys).",
);
